# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./test
# Target is an application:  

INCLUDEPATH += ../src 
INCLUDEPATH += /usr/lib/qt3/include
MAKEFILE = Makefile 
CONFIG += debug \
          warn_on \
          qt \
          console 
TEMPLATE = app 
HEADERS += MyTestSuite.h \
           navigatortest.h 
