# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

QT += qt3support

SUBDIRS += src/epsim \
           src/eppatient \
           src/epui \
           src/stimulator \
	   src/recorder \
           src/navigator

TEMPLATE = subdirs
CONFIG += debug \
warn_on \
qt \
thread
