# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

QT += qt3support

SUBDIRS += src/core \
           src/patient \
           src/hardware \
           src/study \
           src/gui \
           src/stimulator \
	   src/recorder \
           src/navigator \
           src/main \
           src/test

TEMPLATE = subdirs
