# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/stimulator
# Target is a library:  

FORMS += dialbase.ui \
         stimulator.ui 
CONFIG += warn_on \
staticlib \
 debug
TEMPLATE = lib
CONFIG -= release

