EP Simulator Help
* Copyright and License
  EP Simulator is copyright 2006-2010 by EP Studios, Inc.  The
  software license is GPL version 2.
* Disclaimer
  EP Simulator is currently under development.  This Help file is
  probably not very helpful -- yet.
* Websites
** EP Studios, Inc.
   http://www.epstudiossoftware.com/
** Git repository
   http://github.com/mannd/epsimulator
** Screenshots
   https://sourceforge.net/projects/epsimulator/
** EP Studios Blog
   http://www.epstudiossoftware.com/blog
* Differences between EP Simulator and the GE/Prucka System
** Help System
   The Prucka help system opens a PDF version of the manual.  For now,
   EP Simulator Help will open this set of notes.
** Simulator Settings menu
** Navigator blue sidebar
   - This is programmable to version 5 or version 6 appearance.
   - There is no "Mac-Lab" version of the sidebar.
** Patient Information dialog
   Second tab is not Contact, but Physiology.  The Patient Information dialog
   in EP Simulator is used to set up the patient simulation.
** Administrator mode
   - Administrator mode is optional and can be turned off.
   - List, intervals, etc. can only be viewed by administrator.  In Prucka
     lists can be viewed by not edited by non-administrators.
** Optical disk emulation
   Study data can be stored on an actual optical disk, a hard drive
   directory, or a hard drive directory disguised to mimic an optical disk.
** EP List edit boxes
   - There are numbered rows rather than "bullets" preceding items.
   - Administrator mode works differently (see Administrator mode).
   - IMPROVEMENT: List selectors have up/down buttons to rearrange ordered lists.
** Look and feel
   It is not possible (and probably not desirable) to reproduce the exact
   "look and feel" of the Prucka system.  Several properties of the Prucka
   system depend on non-standard handling of windows specific to MS Windows.
   These properties are not easily transferred to a cross-platform system.
   The look and feel will remain recognizable to Prucka users, but will not be
   slavishly exact.
** No ADT option in Navigator
