# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/epsimulator

FORMS += patientinformationdialog.ui 
TRANSLATIONS += epsimulator_de.ts 
IMAGES += hi16-app-epsimulator.png \
          hi32-app-epsimulator.png 
HEADERS += epsimulator.h 
SOURCES += epsimulator.cpp \
           main.cpp 
TEMPLATE += app
CONFIG += release \
warn_on \
thread \
qt
TARGET = ../bin/epsimulator
